version: '3.8'

services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bash_runner
    restart: always
    volumes:
      - ./script.sh:/usr/local/bin/script.sh
