version: '3.9'

services:
  db:
    image: mariadb:10.3
    restart: always
    ports:
      - 40153:3306
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 40154:80
    environment:
      - PMA_ARBITRARY=1
